version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: strapi-connector-bookshelf
    versions:
    - 3.4.5
    - 3.4.6
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
    - 3.5.4
  - dependency-name: strapi-plugin-graphql
    versions:
    - 3.4.5
    - 3.4.6
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
    - 3.5.4
  - dependency-name: strapi-utils
    versions:
    - 3.4.5
    - 3.4.6
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
    - 3.5.4
  - dependency-name: strapi
    versions:
    - 3.4.5
    - 3.4.6
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
    - 3.5.4
  - dependency-name: strapi-admin
    versions:
    - 3.4.5
    - 3.4.6
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
    - 3.5.4
  - dependency-name: strapi-plugin-email
    versions:
    - 3.4.5
    - 3.4.6
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
    - 3.5.4
  - dependency-name: knex
    versions:
    - 0.21.16
    - 0.21.17
    - 0.21.18
    - 0.21.19
    - 0.95.0
    - 0.95.1
    - 0.95.2
    - 0.95.3
  - dependency-name: highlight.js
    versions:
    - 10.5.0
    - 10.6.0
    - 10.7.1
  - dependency-name: urijs
    versions:
    - 1.19.5
  - dependency-name: pg
    versions:
    - 8.5.1
